Additions #2
EclipseMenu/EclipseMenu pull request #7
Opened 2024-07-03 20:06 UTC by zkayns

- Added more mod descriptions
- Credited Uproxide and AzureBluet in mod.json

2024-07-03 20:09 UTC, FireMario211 requested changes
contributors != developers

2024-07-03 20:09 UTC, FireMario211 commented on mod.json
> +	"developers": ["Eclipse Team", "ninXout", "Prevter", "maxnu", "Firee", "SpaghettDev", "Uproxide", "AzureBluet"],
no

2024-07-07 03:09 UTC, FireMario211 approved these changes

2024-07-07 10:01 UTC, Prevter requested changes

2024-07-07 10:01 UTC, Prevter commented on src/hacks/Global/AudioSpeed.cpp
i don't like this, it shouldn't override existing settings

2024-07-07 10:01 UTC, Prevter commented on src/hacks/Bypass/TestmodeBypass.cpp
you broke startpos switcher with this 💔

2024-07-08 17:32 UTC, zkayns commented on src/hacks/Player/AutoKill.cpp
fixed

2024-07-08 17:32 UTC, zkayns commented on src/hacks/Global/AudioSpeed.cpp
removed because its mid

2024-07-08 17:33 UTC, zkayns commented on src/hacks/Bypass/TestmodeBypass.cpp
im not even going to pretend i knew what i was doing when i made it so im just going to remove it

2024-07-24 04:42 UTC, SpaghettDev requested changes

2024-07-24 04:43 UTC, SpaghettDev requested changes

2024-07-24 04:43 UTC, SpaghettDev commented on src/hacks/Player/AutoKill.cpp
> +            auto *playLayer = PlayLayer::get();
you never check if playLayer isnt nullptr (its the case when playtesting in the editor)

2024-07-24 04:47 UTC, SpaghettDev requested changes

2024-07-24 04:47 UTC, SpaghettDev commented on src/hacks/Player/AutoKill.cpp
> +            tab->addFloatToggle("Auto Kill", "player.autokill", 0.f, 100.f, "%.2f%");
no toggle for autokill?

2024-07-24 04:47 UTC, SpaghettDev commented on src/hacks/Player/Autoclicker.cpp
> -            tab->addToggle("Auto Clicker", "player.autoclick")->handleKeybinds();
😨

2024-07-24 04:48 UTC, SpaghettDev commented on src/hacks/Player/AutoKill.cpp
> +            auto *playLayer = PlayLayer::get();
actually you do, but only after you call a method on it rofl

2024-07-24 15:04 UTC, zkayns commented on src/hacks/Player/Autoclicker.cpp
> -            tab->addToggle("Auto Clicker", "player.autoclick")->handleKeybinds();
did i fix it or am i foolish

2024-07-24 15:05 UTC, zkayns commented on src/hacks/Player/AutoKill.cpp
> +            auto *playLayer = PlayLayer::get();
oops

2024-07-24 16:04 UTC, SpaghettDev commented on src/hacks/Player/Autoclicker.cpp
> -            tab->addToggle("Auto Clicker", "player.autoclick")->handleKeybinds();
you did

2024-07-24 16:05 UTC, FireMario211 commented on src/hacks/Player/AutoKill.cpp
> +            tab->addFloatToggle("Auto Kill", "player.autokill", 0.f, 100.f, "%.2f%");
thats how addFloatToggle works @SpaghettDev

2024-07-24 19:48 UTC, Prevter commented on src/modules/gui/styles/megahack.hpp
> +            if (radioButton->getValue()) ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1, 1, 1, 1));
memory leak 🥰

2024-07-26 02:57 UTC, SpaghettDev commented on src/modules/gui/styles/megahack.hpp
> +            if (radioButton->getValue()) ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1, 1, 1, 1));
its ok prevter the whole menu is a memory leak :)

2024-07-26 02:58 UTC, merged